server:
  port: 8080

spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:approximately_normal.db
    username: root
    password: root
  application:
    name: approximately-normal-backend
  jpa:
    #database: mysql
    database-platform: com.backend.config.SQLiteDialect
    show-sql: false
    format-sql: true
    use-sql-comment: true
    hibernate:
        ddl-auto: update #update
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        #dialect: com.backend.config.SQLiteDialect
        dialect: org.hibernate.dialect.SQLiteDialect

eureka:
  client:
    service-url:
      default-zome: http://localhost:8761/eureka
